### ISSUE TITLE
Can't view orders from admin

### ISSUE THREAD

**Issue by Redlessracoon** [JamesRamm/longclaw#131]
* longclaw version: 0.2.0
* Django version: 1.10.8
* Python version: 3.6

### Description

After making a checkout with Base Payment, the new order is added in order list. But.. when I click on one of them, it just shows that circle. The reason is that, api/order/<pk> returns 404 Error

![image](https://user-images.githubusercontent.com/20662371/35690844-3c32162c-0777-11e8-809f-b1b7b56678b2.png)

**Comment by Redlessracoon** [comment]
I found that, if I access it directly

`http://127.0.0.1:8000/api/order/4/`

instead of

`http://127.0.0.1:8000/admin/longclaworders/order/detail/4/api/order/4`

I can access that json in REST framework

Maybe I'm just not really understanding how it must work.

**Comment by JamesRamm** [comment]
Looks like a problem with using a relative URL. 
Possibly the URL fragments for the API need to be prepended with a forward slash

**Comment by BenSturmfels** [comment]
Ah yes, this has kept me entertained this afternoon. :) I guess it must work ok if you have your URLConfs set up in some precise way, but as soon as you vary it a little, things break. It looks like there are two issues here with the relative URL:

1. The URLConf for 'longclaw_orders' is relative all the way; there's no `^` to anchor the regular expression. That's fine in theory, but not how most Django apps do it, so very confusing to troubleshoot. For example, this 404s for me, as it's being captured by Wagtail admin in my setup:

    /admin/longclaworders/order/detail/1/api/order/1/

But this works:

  /api/order/1/

And so does this:

  /aaaaaaaa/api/order/1/

2. The JavaScript needs to request an absolute URL, eg. `/api/order/1/` rather than `api/order/1`.

It all gets a bit complicated with JavaScript in the mix, doesn't it. I'll see if I can come up with a small patch.
