### ISSUE TITLE
Migrate: error cannot import name 'detail_route'

### ISSUE THREAD

**Issue by levanlau** [JamesRamm/longclaw#248]
# ISSUE

* longclaw version: lastest
* Django version: 2.2
* Python version: 3.5

## Description

When i do migrate to db, there is an error "cannot import name 'detail_route'" from library rest_framework.decorators. I think rest_framework without function 'detail_route' and 'list_route'.
Please reupdate data from /longclaw/basket/api.py. Thank you !

**Comment by JamesRamm** [comment]
@deliseev.
This is almost certainly because the version of DRF you have installed is 3.10 or greater.
The current version of DRF for longclaw is 3.9.2 - ``list_route`` and ``detail_route`` are available (although deprecated): https://www.django-rest-framework.org/community/3.8-announcement/

Please check the version of DRF you have installed and correct it to 3.9.2
I will close this; you can track 3.10 support of DRF in #256

**Comment by JamesRamm** [comment]
@levanlau 
The relevant updates have now been pushed to master
