### ISSUE TITLE
Shipping address default

### ISSUE THREAD

**Issue by alexfromvl** [JamesRamm/longclaw#42]
Add to default SHIPPING ADDRESS - Goods shall be shipped to the Buyer on Ex–warehouse delivery terms.

The problem is that the shipping address field is mandatory. If there is not a single field, then it's impossible to create an order.

Adding an address will solve the problem of creating test orders.

**Comment by alexfromvl** [comment]
Add PR #43

**Comment by JamesRamm** [comment]
Hi
Thanks for the contribution! 
I think that exposing the ``Address`` model to the wagtail admin right now would make it relatively confusing and doesnt go as far as needed. I'd prefer a more comprehensive solution around creating 'customers'. I think this would be some future work (perhaps a 0.2.0 or 0.3.0 release).

I agree that some way to create Orders from the wagtail admin is required. This can either be by:

- Improving the current Order admin so that the address can be explicitly added in the order, rather than selecting an existing one (preferred, but more complex)
- Providing a demo/default address in a migration (easy, perhaps not ideal)

For now, a work around would be to create an address manually in the django shell::

```python
   from longclaw.longclawshipping.models import Address

   address = Address(name='test', line_1='test', city='test', postcode='test', country='test')
   address.save()
```
The address will then be available in the wagtail admin.

To implement unit tests, you can submit a blank address in the request data, something like:
 
```python
   
    data = {
        'address': {
            'shipping_name': '',
            'shipping_address_line_1': '',
            'shipping_address_city': '',
            'shipping_address_zip': '',
            'shipping_address_country': '',
            'billing_name': '',
            'billing_address_line_1': '',
            'billing_address_city': '',
            'billing_address_zip': '',
            'billing_address_country': ''
        },
        'email': 'test@test.com',
        'shipping_rate': 0
    }
    self.client.post(reverse('checkout'), data)

```
