### ISSUE TITLE
Customizing ProductIndex

### ISSUE THREAD

**Issue by vanderstel** [JamesRamm/longclaw#76]
* longclaw version: 0.1.1
* Django version: 1.10.7
* Python version: 2.7

### Description

It would be great to have a way of passing variables into the ProductIndex template (like Wagtail's get_context method) to facilitate features such as pagination.

**Comment by JamesRamm** [comment]
I've moved this back to 1.0 as it has repercussions for #47 and potentially #49 and #53.
Together these a basically an overhaul of the products app - which I think is needed - and will form the major change taking us to 1.0.

On the face of it, `ProductIndex` is not used elsewhere in longclaw, however, `Product` is its' only possible child and `ProductVariant`'s are supposed to be children of `Product`. `ProductVariant` is customizable.

Potentially we could use the same customisation system for `ProductIndex` and `Product` as we are using for `ProductVariant`.
However, I am not a fan of having to specify in the settings where your `ProductIndex`, `Product` and `ProductVariant` models lie. A nicer solution, if possible, would be to simply inherit from some base and have longclaw figure out the rest.

**Comment by JamesRamm** [comment]
One possible easy solution for this. If we remove the `parent_page_type` limitation on `longclawproducts.models.Product`  then it should be safe to simply create your own index page model:

class MyProductIndex(Page):
    subpage_types = ('longclawproducts.Product',)

And create your `Product` instances under this. This is possible since `ProductIndex` isn't actually used anywhere else in the framework. It is only the `parent_page_types = ['longclawproducts.ProductIndex']` limitation on `Product` that stops you creating your own index model. 

2 pitfalls of this approach:

- It doesn't solve anything for #47 where we would like to customise products. It doesn't necessarily hinder it, but might not be the optimal solution for both.
- You can then create `Product` instances under *any* `Page`. This is not necessarily a problem, but you could end up with cases where you e.g. accidentally create a `Product` under a `BlogIndex` which doesnt make sense semantically. 

I am undecided whether either of those should be considered problematic issues or not.

**Comment by JamesRamm** [comment]
@vanderstel if you have time, do have a look at #86 and let me know if it would address your needs.
Cheers.
