### ISSUE TITLE
Price Calculations

### ISSUE THREAD

**Issue by rams3377** [JamesRamm/longclaw#84]
* longclaw 0.2.0:
* Django 1.10.7:
* Python 3.5:

### Description

Great app, I was wondering (and forgive me if already present) are there any plans to add flexible price calculations. For instance an overridable method (get_price() -> price) or property that will allow prices to be generated at the developers discretion or merchants?

**Comment by JamesRamm** [comment]
@rams3377 
Thanks for the suggestion. You can accomplish this already, however I can see a possibility to make it easier. 

First, to do it already. If you have used `longclaw start` to create your project, you will have in your app a `products` app, with `ProductVariant` model. This inherits from `ProductVariantBase`, which provides a few fields that longclaw expects to exist, among them is `price`. You can simply *not* inherit from `ProductVariantBase` and provide the needed fields yourself. 

`ProductVariantBase` looks like:

```python

@python_2_unicode_compatible
class ProductVariantBase(models.Model):
    """
    Base model for creating product variants
    """
    price = models.DecimalField(max_digits=12, decimal_places=2)
    ref = models.CharField(max_length=32)
    stock = models.IntegerField(default=0)
    slug = AutoSlugField(
        separator='',
        populate_from=('product', 'ref'),
        )
    class Meta:
        abstract = True

    def __str__(self):
        return "{} - {}".format(self.product.title, self.ref)

    def get_product_title(self):
        return self.product.title
```
So you could define a similar thing, but use a `@property` function for the `price` attribute instead of a django model field. `price` would need to be a property as longclaw expects to be able to access it as an instance attribute.

Now, for a possible future change. 
I could see the `price` field of `ProductVariantBase` being changed to `base_price` and a `price` property being added instead, which will just return `base_price`. That way you can still inherit from `ProductVariantBase` and just override the `price` property.

**Comment by rams3377** [comment]
Awesome, I'll use the recommendation you made for the time being. Appreciate it!
